In [1]:
import numpy as np
#np.set_printoptions(threshold=np.nan)

file = open("/home/saklain/direction.txt", "r") 
t=0
mainlist=[]
mylist = []

cnt=0
for line in file:
    if(cnt==0):
        line=float(line.replace("\n",""))
        mylist.append(line)
    if(cnt==1):
        line=float(line.replace("\n",""))
        mylist.append(line)
    if(cnt==3):
        line=float(line.replace("\n",""))
        mylist.append(line)
    
    t=t+1
    cnt=cnt+1
    if cnt==7:
        cnt=0
    if(t%28==0):
        t=0
        a=np.asarray(mylist)
        mainlist.append(a)
        #print(a)
        mylist.clear()
        #print("*******")
        
data=np.asarray(mainlist)
print(data)
print(data.size)
print(type(data))

ar = np.nonzero(data == -156.535598)
print("Their indices are ", np.unique(ar[0]).size)
print("Their indices are ", type(ar[0]))
print(np.unique(ar[0]).size)

while np.nonzero(data == -156.535598):
    arr = np.nonzero(data == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    data=np.delete(data, np.unique(arr[0])[0], 0)
    #print("Their indices are------ ", np.unique(arr[0])[0])    

    


ar = np.nonzero(data == -156.535598)
print("Their indices are------ ", np.unique(ar[0]).size)    
print(data.size/12)

[[20.000653 16.008143  8.770485 ... 23.27594  21.603313 13.468522]
 [19.540455 17.438957  8.990967 ... 23.01458  21.968106 13.742793]
 [18.940627 17.41331   9.396025 ... 22.788254 21.921892 13.772426]
 ...
 [18.141149 20.662345  5.249352 ... 20.610944 23.814913 15.090571]
 [17.871034 21.468738  5.98376  ... 20.558847 24.190584 15.134746]
 [18.589421 21.409892  6.006687 ... 20.927528 24.20962  15.542816]]
72000
<class 'numpy.ndarray'>
Their indices are  89
Their indices are  <class 'numpy.ndarray'>
89
zero
Their indices are------  0
5911.0


In [4]:
from sklearn.cluster import KMeans
import numpy as np
np.set_printoptions(threshold=np.nan)

kmeans = KMeans(n_clusters=2, random_state=0).fit(data)

In [16]:
cnt=0
for i in range(3000):
    #print(kmeans.labels_[i])
    if(kmeans.labels_[i]==1):
        cnt=cnt+1

print(cnt)

cnt2=0
for i in range(2911):
    #print(kmeans.labels_[i])
    if(kmeans.labels_[3000+i]==0):
        cnt2=cnt2+1

print(cnt2)
#kmeans.cluster_centers_

141
816
