In [3]:
#filenames = ['/home/saklain/rad/balc.txt','/home/saklain/rad/door.txt','/home/saklain/rad/midroom.txt']
#with open('/home/saklain/rad/traindata.txt', 'w') as outfile:
 #   for fname in filenames:
  #      with open(fname) as infile:
   #         outfile.write(infile.read())

In [4]:
#TRAINING DATA
import numpy as np
file = open("/home/saklain/rad/traindata.txt", "r") 
t=0
mainlist=[]
mylist = []
k=-156.535598
cnt=0
for line in file:
    if(cnt==0):
        line=float(line.replace("\n",""))
        mylist.append(line)
    if(cnt==1):
        line=float(line.replace("\n",""))
        mylist.append(line)
    if(cnt==3):
        line=float(line.replace("\n",""))
        mylist.append(line)
    
    t=t+1
    cnt=cnt+1
    if cnt==7:
        cnt=0
    if(t%28==0):
        t=0
        a=np.asarray(mylist)
        mainlist.append(a)
        #print(a)
        mylist.clear()
        #print("*******")
        
data=np.asarray(mainlist)
print(data)
print(data.size)
print(type(data))
#data=np.delete(data, 3048, 0)
#data=np.delete(data, 3568, 0)
print("Their indices are ", np.nonzero(data == -156.535598))


[[ 7.839827 18.593677  4.169149 ... 15.006199 22.493886 13.255091]
 [ 9.494929 20.803282  4.310922 ... 14.930078 23.816222 13.355334]
 [10.365546 21.642272  4.634742 ... 15.748691 24.289007 13.776883]
 ...
 [20.554249 18.57388  11.797091 ... 23.251001 20.868045 17.95352 ]
 [17.060326 15.42661   7.872376 ... 21.590985 20.233291 17.240152]
 [19.688239 17.789868  9.669624 ... 22.972672 21.340896 18.129271]]
3600000
<class 'numpy.ndarray'>
Their indices are  (array([    80,     80,     80, ..., 221081, 221081, 221081]), array([ 1,  2,  4, ...,  8, 10, 11]))


In [5]:
print(data.size/12)
print(type(data))
#data=np.delete(data, 3048, 0)
#data=np.delete(data, 3568, 0)
print("test1 err ", np.unique(np.nonzero(data == -156.535598)[0]).size)


300000.0
<class 'numpy.ndarray'>
test1 err  2051


In [6]:
print(data.size/12)
sp = np.split(data, 3)
data1= sp[0]
data2= sp[1]
data3= sp[2]

print(data1.size/12)
#print(data1)
print(data2.size/12)
#print(data2)
print(data3.size/12)

test1 = data1[85000:100000]
print(test1.size/12)
train1 = data1[0:85000]
print(train1.size/12)







test2 = data2[85000:100000]
print(test2.size/12)
train2 = data2[0:85000]
print(train2.size/12)

test3 = data3[85000:100000]
print(test3.size/12)
train3 = data3[0:85000]
print(train3.size/12)


300000.0
100000.0
100000.0
100000.0
15000.0
85000.0
15000.0
85000.0
15000.0
85000.0


In [7]:
print("test1 err ", np.unique(np.nonzero(test1 == -156.535598)[0]).size)
print("train1 err ", np.unique(np.nonzero(train1 == -156.535598)[0]).size)
print("test2 err ", np.unique(np.nonzero(test2 == -156.535598)[0]).size)
print("train2 err ", np.unique(np.nonzero(train2 == -156.535598)[0]).size)
print("test3 err ", np.unique(np.nonzero(test3 == -156.535598)[0]).size)
print("train3 err ", np.unique(np.nonzero(train3 == -156.535598)[0]).size)

print("test1 err ", 15000-np.unique(np.nonzero(test1 == -156.535598)[0]).size)
print("train1 err ", 85000-np.unique(np.nonzero(train1 == -156.535598)[0]).size)
print("test2 err ", 15000-np.unique(np.nonzero(test2 == -156.535598)[0]).size)
print("train2 err ", 85000-np.unique(np.nonzero(train2 == -156.535598)[0]).size)
print("test3 err ", 15000-np.unique(np.nonzero(test3 == -156.535598)[0]).size)
print("train3 err ", 85000-np.unique(np.nonzero(train3 == -156.535598)[0]).size)



test1 err  143
train1 err  1221
test2 err  10
train2 err  479
test3 err  0
train3 err  198
test1 err  14857
train1 err  83779
test2 err  14990
train2 err  84521
test3 err  15000
train3 err  84802


In [8]:
while np.nonzero(train1 == -156.535598):
    arr = np.nonzero(train1 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    train1=np.delete(train1, np.unique(arr[0])[0], 0)
    

    
while np.nonzero(train2 == -156.535598):
    arr = np.nonzero(train2 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    train2=np.delete(train2, np.unique(arr[0])[0], 0)
    
    
while np.nonzero(train3 == -156.535598):
    arr = np.nonzero(train3 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    train3=np.delete(train3, np.unique(arr[0])[0], 0)
    
while np.nonzero(test1 == -156.535598):
    arr = np.nonzero(test1 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    test1=np.delete(test1, np.unique(arr[0])[0], 0)

while np.nonzero(test2 == -156.535598):
    arr = np.nonzero(test2 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    test2=np.delete(test2, np.unique(arr[0])[0], 0)

while np.nonzero(test3 == -156.535598):
    arr = np.nonzero(test3 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    test3=np.delete(test3, np.unique(arr[0])[0], 0)


zero
zero
zero
zero
zero
zero


In [9]:
a=test1.size/12
print(a)
b=train1.size/12
print(b)

c=test2.size/12
print(c)
d=train2.size/12
print(d)

e=test3.size/12
print(e)
f=train3.size/12
print(f)

trainset = np.append(train1,train2,axis=0)
trainset = np.append(trainset,train3,axis=0)

testset = np.append(test1,test2,axis=0)
testset = np.append(testset,test3,axis=0)

print(trainset.size/12)
print(testset.size/12)






14857.0
83779.0
14990.0
84521.0
15000.0
84802.0
253102.0
44847.0


In [10]:
import numpy as np
temp = []
out = []

for i in range(int(b)):
    temp.append(0)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(int(d)):
    temp.append(1)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(int(f)):
    temp.append(2)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
        
labels=np.asarray(out)
print(labels)
print(labels.size)
print(type(labels))

[[0]
 [0]
 [0]
 ...
 [2]
 [2]
 [2]]
253102
<class 'numpy.ndarray'>


In [11]:
import numpy as np
temp = []
out = []

for i in range(int(a)):
    temp.append(0)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(int(c)):
    temp.append(1)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(int(e)):
    temp.append(2)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()


labels_test=np.asarray(out)
print(labels_test)
print(labels_test.size)
print(type(labels_test))

[[0]
 [0]
 [0]
 ...
 [2]
 [2]
 [2]]
44847
<class 'numpy.ndarray'>


In [13]:

import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
# For a single-input model with 10 classes (categorical classification):

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=12))
model.add(Dense(16, activation='softmax'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

import numpy as np

print(trainset.size/12)
print(labels.size)
print(testset.size/12)
print(labels_test.size)

# Convert labels to categorical one-hot encoding
one_hot_labels = keras.utils.to_categorical(labels, num_classes=3)
one_hot_labels_test = keras.utils.to_categorical(labels_test, num_classes=3)

# Train the model, iterating on the data in batches of 32 samples
model.fit(trainset, one_hot_labels, epochs=50,validation_data=(testset, one_hot_labels_test), batch_size=32)
model.save('/home/saklain/ThesisCNN/newmodel2.h5')

#score = model.evaluate(data_test,one_hot_labels_test, batch_size=32)
#print(score)



253102.0
253102
44847.0
44847
Train on 253102 samples, validate on 44847 samples
Epoch 1/50
253102/253102 [==============================] - 17s 66us/step - loss: 0.5186 - acc: 0.7986 - val_loss: 0.2065 - val_acc: 0.9657
Epoch 2/50
253102/253102 [==============================] - 17s 68us/step - loss: 0.3823 - acc: 0.8546 - val_loss: 0.2102 - val_acc: 0.9482
Epoch 3/50
253102/253102 [==============================] - 19s 74us/step - loss: 0.3503 - acc: 0.8681 - val_loss: 0.2152 - val_acc: 0.9299
Epoch 4/50
253102/253102 [==============================] - 18s 70us/step - loss: 0.3249 - acc: 0.8794 - val_loss: 0.1308 - val_acc: 0.9640
Epoch 5/50
253102/253102 [==============================] - 18s 72us/step - loss: 0.3030 - acc: 0.8884 - val_loss: 0.1022 - val_acc: 0.9808
Epoch 6/50
253102/253102 [==============================] - 20s 78us/step - loss: 0.2878 - acc: 0.8941 - val_loss: 0.1401 - val_acc: 0.9669
Epoch 7/50
253102/253102 [==============================] - 18s 71us/step - los

In [14]:
score = model.evaluate(testset,one_hot_labels_test, batch_size=32)
print(score)

44847/44847 [==============================] - 1s 20us/step
[0.15495382977409097, 0.9624724061810155]
