100000.0
<class 'numpy.ndarray'>
Their indices are  1364
Their indices are  <class 'numpy.ndarray'>
1364
zero
Their indices are------  0
98636.0


In [36]:
filenames = ['/home/saklain/rad/balc.txt','/home/saklain/rad/door.txt','/home/saklain/rad/midroom.txt']
with open('/home/saklain/rad/traindata.txt', 'w') as outfile:
    for fname in filenames:
        with open(fname) as infile:
            outfile.write(infile.read())

In [63]:
#TRAINING DATA
import numpy as np
file = open("/home/saklain/rad/traindata.txt", "r") 
t=0
mainlist=[]
mylist = []
k=-156.535598
cnt=0
for line in file:
    if(cnt==0):
        line=float(line.replace("\n",""))
        mylist.append(line)
    if(cnt==1):
        line=float(line.replace("\n",""))
        mylist.append(line)
    if(cnt==3):
        line=float(line.replace("\n",""))
        mylist.append(line)
    
    t=t+1
    cnt=cnt+1
    if cnt==7:
        cnt=0
    if(t%28==0):
        t=0
        a=np.asarray(mylist)
        mainlist.append(a)
        #print(a)
        mylist.clear()
        #print("*******")
        
data=np.asarray(mainlist)
print(data)
print(data.size)
print(type(data))
#data=np.delete(data, 3048, 0)
#data=np.delete(data, 3568, 0)
print("Their indices are ", np.nonzero(data == -156.535598))


[[ 7.839827 18.593677  4.169149 ... 15.006199 22.493886 13.255091]
 [ 9.494929 20.803282  4.310922 ... 14.930078 23.816222 13.355334]
 [10.365546 21.642272  4.634742 ... 15.748691 24.289007 13.776883]
 ...
 [20.554249 18.57388  11.797091 ... 23.251001 20.868045 17.95352 ]
 [17.060326 15.42661   7.872376 ... 21.590985 20.233291 17.240152]
 [19.688239 17.789868  9.669624 ... 22.972672 21.340896 18.129271]]
3600000
<class 'numpy.ndarray'>
Their indices are  (array([    80,     80,     80, ..., 221081, 221081, 221081]), array([ 1,  2,  4, ...,  8, 10, 11]))


In [65]:
print(data.size/12)
print(type(data))
#data=np.delete(data, 3048, 0)
#data=np.delete(data, 3568, 0)
print("test1 err ", np.unique(np.nonzero(data == -156.535598)[0]).size)


300000.0
<class 'numpy.ndarray'>
Their indices are  2051


In [82]:
print(data.size/12)
sp = np.split(data, 3)
data1= sp[0]
data2= sp[1]
data3= sp[2]

print(data1.size/12)
#print(data1)
print(data2.size/12)
#print(data2)
print(data3.size/12)

test1 = data1[0:15000]
print(test1.size/12)
train1 = data1[15000:100000]
print(train1.size/12)


test2 = data2[0:15000]
print(test2.size/12)
train2 = data2[15000:100000]
print(train2.size/12)

test3 = data3[0:15000]
print(test3.size/12)
train3 = data3[15000:100000]
print(train3.size/12)


300000.0
100000.0
100000.0
100000.0
15000.0
85000.0
15000.0
85000.0
15000.0
85000.0


In [86]:
print("test1 err ", np.unique(np.nonzero(test1 == -156.535598)[0]).size)
print("train1 err ", np.unique(np.nonzero(train1 == -156.535598)[0]).size)
print("test2 err ", np.unique(np.nonzero(test2 == -156.535598)[0]).size)
print("train2 err ", np.unique(np.nonzero(train2 == -156.535598)[0]).size)
print("test3 err ", np.unique(np.nonzero(test3 == -156.535598)[0]).size)
print("train3 err ", np.unique(np.nonzero(train3 == -156.535598)[0]).size)

print("test1 err ", 15000-np.unique(np.nonzero(test1 == -156.535598)[0]).size)
print("train1 err ", 85000-np.unique(np.nonzero(train1 == -156.535598)[0]).size)
print("test2 err ", 15000-np.unique(np.nonzero(test2 == -156.535598)[0]).size)
print("train2 err ", 85000-np.unique(np.nonzero(train2 == -156.535598)[0]).size)
print("test3 err ", 15000-np.unique(np.nonzero(test3 == -156.535598)[0]).size)
print("train3 err ", 85000-np.unique(np.nonzero(train3 == -156.535598)[0]).size)



test1 err  367
train1 err  997
test2 err  192
train2 err  297
test3 err  197
train3 err  1
test1 err  14633
train1 err  84003
test2 err  14808
train2 err  84703
test3 err  14803
train3 err  84999


[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [87]:
while np.nonzero(train1 == -156.535598):
    arr = np.nonzero(train1 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    train1=np.delete(train1, np.unique(arr[0])[0], 0)
    

    
while np.nonzero(train2 == -156.535598):
    arr = np.nonzero(train2 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    train2=np.delete(train2, np.unique(arr[0])[0], 0)
    
    
while np.nonzero(train3 == -156.535598):
    arr = np.nonzero(train3 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    train3=np.delete(train3, np.unique(arr[0])[0], 0)
    
while np.nonzero(test1 == -156.535598):
    arr = np.nonzero(test1 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    test1=np.delete(test1, np.unique(arr[0])[0], 0)

while np.nonzero(test2 == -156.535598):
    arr = np.nonzero(test2 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    test2=np.delete(test2, np.unique(arr[0])[0], 0)

while np.nonzero(test3 == -156.535598):
    arr = np.nonzero(test3 == -156.535598)
    #print(np.unique(arr[0]).size)
    if np.unique(arr[0]).size==0:
        print("zero")
        break
    test3=np.delete(test3, np.unique(arr[0])[0], 0)


zero
zero
zero
zero
zero
zero
14633.0
84003.0
14808.0
84703.0
14803.0
84999.0


In [109]:
print(test1.size/12)
print(train1.size/12)


print(test2.size/12)
print(train2.size/12)

print(test3.size/12)
print(train3.size/12)

trainset = np.append(train1,train2,axis=0)
trainset = np.append(trainset,train3,axis=0)
testset = np.append(test1,test2,axis=0)
testset = np.append(testset,test3,axis=0)

print(trainset.size/12)
print(testset.size/12)






14633.0
84003.0
14808.0
84703.0
14803.0
84999.0
253705.0
44244.0


In [93]:
import numpy as np
temp = []
out = []

for i in range(84003):
    temp.append(0)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(84703):
    temp.append(1)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(84999):
    temp.append(2)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
        
labels=np.asarray(out)
print(labels)
print(labels.size)
print(type(labels))

[[0]
 [0]
 [0]
 ...
 [2]
 [2]
 [2]]
253705
<class 'numpy.ndarray'>


In [95]:
import numpy as np
temp = []
out = []

for i in range(14633):
    temp.append(0)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(14808):
    temp.append(1)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()
    
for i in range(14803):
    temp.append(2)
    tempfin=np.asarray(temp)
    out.append(tempfin)
    temp.clear()


labels_test=np.asarray(out)
print(labels_test)
print(labels_test.size)
print(type(labels_test))

[[0]
 [0]
 [0]
 ...
 [2]
 [2]
 [2]]
44244
<class 'numpy.ndarray'>


In [ ]:

import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
# For a single-input model with 10 classes (categorical classification):

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=12))
model.add(Dense(3, activation='softmax'))
model.add(Dense(32, activation='softmax'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

import numpy as np

print(trainset.size/12)
print(labels.size)
print(testset.size/12)
print(labels_test.size)

# Convert labels to categorical one-hot encoding
one_hot_labels = keras.utils.to_categorical(labels, num_classes=3)
one_hot_labels_test = keras.utils.to_categorical(labels_test, num_classes=3)

# Train the model, iterating on the data in batches of 32 samples
model.fit(trainset, one_hot_labels, epochs=300,validation_data=(testset, one_hot_labels_test), batch_size=32)
model.save('/home/saklain/ThesisCNN/newmodel.h5')

#score = model.evaluate(data_test,one_hot_labels_test, batch_size=32)
#print(score)



253705.0
253705
44244.0
44244
Train on 253705 samples, validate on 44244 samples
Epoch 1/300
253705/253705 [==============================] - 6s 22us/step - loss: 0.5454 - acc: 0.7801 - val_loss: 1.2844 - val_acc: 0.5194
Epoch 2/300
253705/253705 [==============================] - 5s 21us/step - loss: 0.2984 - acc: 0.9071 - val_loss: 1.5861 - val_acc: 0.4370
Epoch 3/300
253705/253705 [==============================] - 5s 21us/step - loss: 0.2670 - acc: 0.9133 - val_loss: 1.0892 - val_acc: 0.5859
Epoch 4/300
253705/253705 [==============================] - 6s 25us/step - loss: 0.2445 - acc: 0.9182 - val_loss: 1.1235 - val_acc: 0.5932
Epoch 5/300
253705/253705 [==============================] - 7s 26us/step - loss: 0.2313 - acc: 0.9218 - val_loss: 1.4663 - val_acc: 0.4661
Epoch 6/300
253705/253705 [==============================] - 5s 22us/step - loss: 0.2209 - acc: 0.9247 - val_loss: 1.2374 - val_acc: 0.5136
Epoch 7/300
253705/253705 [==============================] - 6s 22us/step - los

253705/253705 [==============================] - 6s 22us/step - loss: 0.1601 - acc: 0.9470 - val_loss: 1.0704 - val_acc: 0.6111
Epoch 59/300
253705/253705 [==============================] - 6s 22us/step - loss: 0.1595 - acc: 0.9473 - val_loss: 1.2932 - val_acc: 0.5856
Epoch 60/300
253705/253705 [==============================] - 6s 24us/step - loss: 0.1592 - acc: 0.9480 - val_loss: 1.1311 - val_acc: 0.5958
Epoch 61/300
253705/253705 [==============================] - 6s 23us/step - loss: 0.1590 - acc: 0.9478 - val_loss: 1.1530 - val_acc: 0.6017
Epoch 62/300
253705/253705 [==============================] - 5s 21us/step - loss: 0.1588 - acc: 0.9482 - val_loss: 1.0285 - val_acc: 0.6404
Epoch 63/300
253705/253705 [==============================] - 5s 19us/step - loss: 0.1579 - acc: 0.9490 - val_loss: 1.3248 - val_acc: 0.6072
Epoch 64/300
253705/253705 [==============================] - 5s 20us/step - loss: 0.1569 - acc: 0.9486 - val_loss: 1.0791 - val_acc: 0.6193
Epoch 65/300
253705/253705

In [118]:
score = model.evaluate(testset,one_hot_labels_test, batch_size=32)
print(score)

44244/44244 [==============================] - 0s 5us/step
[1.1294365176325971, 0.5302413886628695]
